---
title: "case_control_afterclass"
author: "Yingyu Cui"
date: "2024-10-15"
output: html_document
---
```{r setup}
library(tidyverse)
```

load data 
```{r load airbnb data}
library(p8105.datasets)

data(nyc_airbnb)
```
understand the dataset and the variables 
```{r understand the dataset}
str(nyc_airbnb)
```
```{r understand the variables 2}
nyc_airbnb |> 
  count(room_type)
nyc_airbnb |> 
  count(neighbourhood_group)
```
install leaflet package

```{r library leaflet}
library(leaflet)
```
an example
```{r example}
institution <- c("Amherst College", "Hampshire College", "Mount Holyoke College", "Smith College", "University of Massachusetts")
lat <- c(42.3709, 42.325079, 42.255586, 42.318119, 42.3912)
lng <- c(-72.5170, -72.530837, -72.574503, -72.638139, -72.5267)
students <- c(1792, 1175, 2255, 2600, 28635)
label <- paste0("<b>", institution, "</b><br>", students, " students", sep="")
ds <- dplyr::tibble(institution, lat, lng, students, label)
dplyr::glimpse(ds)
```

```{r leaflet}
m <- leaflet(ds) |> 
  addTiles() |> 
  addMarkers(~lng, ~lat, popup = ~ label)
m
```

```{r summarize}
nyc_airbnb |> 
  group_by(neighbourhood_group, room_type) |> 
  summarize(median_price = median(price)) 
```
```{r summarize 2}
nyc_airbnb %>%
  group_by(neighbourhood_group) %>%
  summarise(total_reviews = sum(number_of_reviews, na.rm = TRUE)) 
```

```{r summarize 3}
pal <- colorNumeric(
  palette = "viridis",
  domain = nyc_airbnb$review_scores_location)

n <- nyc_airbnb |> 
  filter(
    neighbourhood_group == "Manhattan",
    price < 1000) |> 
  leaflet() |>  
  addProviderTiles(providers$CartoDB.Positron) |> 
  addCircleMarkers(
    ~lat, ~long, 
    color = ~ pal(review_scores_location), radius = 2)
n
```
